"""Deterministic paintable arena meshes. Coordinates match BuildInk / InkSurface."""
from pathlib import Path
import math
root=Path(__file__).resolve().parents[1]/'Resources/Models/Ink'
root.mkdir(parents=True,exist_ok=True)
surfaces=[((x,0,z),(220,0,0),(0,0,240)) for z in (-340,-100,140) for x in (-330,-110,110)]
for i,(o,u,v) in enumerate(surfaces):
    positions=[o,tuple(o[j]+u[j] for j in range(3)),tuple(o[j]+u[j]+v[j] for j in range(3)),tuple(o[j]+v[j] for j in range(3))]
    # Importer mirrors X, reverses winding, and flips UV V.
    lines=['# Paint atlas surface; generated by tests/GenerateInkSurfaces.py']
    lines += [f'v {-x} {y} {z}' for x,y,z in positions]
    for x,y in ((0,0),(1,0),(1,1),(0,1)):
        lines.append(f'vt {((i%4)*128+.5+x*127)/512} {1-((i//4)*128+.5+y*127)/512}')
    n=(-(u[1]*v[2]-u[2]*v[1]),-(u[2]*v[0]-u[0]*v[2]),-(u[0]*v[1]-u[1]*v[0]));length=math.sqrt(sum(a*a for a in n))
    lines += ['vn '+' '.join(str(a/length) for a in (-n[0],n[1],n[2])),'f 1/1/1 2/2/1 3/3/1','f 1/1/1 3/3/1 4/4/1']
    (root/f'surface{i}.obj').write_text('\n'.join(lines)+'\n')
